# Generated by Django 3.2.5 on 2021-07-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
