# Generated by Django 3.2.5 on 2021-07-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_url',
            new_name='img_rel_url',
        ),
    ]
