# Generated by Django 3.2.5 on 2021-07-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_img_url_article_img_rel_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_rel_url',
            new_name='img_url',
        ),
    ]
