# Generated by Django 3.2.5 on 2021-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.CharField(default='Collaborations externes', max_length=264),
        ),
    ]
