# Generated by Django 3.2.5 on 2021-08-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='languages',
            field=models.CharField(default='Français', max_length=264),
        ),
    ]
