# Generated by Django 3.2.5 on 2021-08-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='languages',
            new_name='language',
        ),
    ]
