# Generated by Django 3.2.5 on 2021-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_languages_article_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=264)),
                ('date', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
