# Generated by Django 3.2.5 on 2021-12-10 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('articles', '0016_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name'),
        ),
    ]
